server.port: 9090

auth:
  enabled: true
  jwt.key.set.uri: http://localhost:8080/oauth2/jwks

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/RetailPulseDB
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
