server.port: 8080

auth:
  enabled: true
  jwt.key.set.uri: http://localhost:8080/oauth2/jwks

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/RetailPulseDB
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    root: INFO
    com.retailpulse: DEBUG
  file:
    name: logs/retailpulse.log
