name: Java CI with Maven

on:
  push:
    branches: 
      - "casperdev"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
   
    - name: Clean
      run: mvn clean --file backend/pom.xml

    - name: Build
      run: mvn --batch-mode -DskipTests package --file backend/pom.xml
    
    - name: Test
      run: mvn --batch-mode test --file backend/pom.xml