name: Java CI with Maven

on:
  push:
    branches: 
      - "galvin_dev"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Display Maven version
      run: mvn -v
    - name: Compile and run unit tests on specific folder
      run: mvn compile -Dtest=com.retailpulse.controller.** test --file backend/pom.xml -X